
vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-maven
    - vscjava.vscode-java-dependency
    - vscjava.vscode-spring-boot-dashboard
    - vmware.vscode-spring-boot
    - vmware.vscode-spring-cli
    - vscjava.vscode-spring-initializr
    - vscjava.vscode-java-test
